version: "3.9"

services:
  db:
    image: supabase/postgres:15.6.1.146
    container_name: supabase-db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data:Z
    restart: unless-stopped
    ports:
      - "5433:5432"  # ホストの5433をコンテナの5432にマッピング

  meta:
    image: supabase/postgres-meta:v0.84.2
    container_name: supabase-meta
    depends_on:
      db:
        condition: service_healthy
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: db
      PG_META_DB_PORT: 5432
      PG_META_DB_NAME: ${POSTGRES_DB}
      PG_META_DB_USER: postgres
      PG_META_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"  # ホストの8080を使用
    restart: unless-stopped

  rest:
    image: postgrest/postgrest:v12.2.0
    container_name: supabase-rest
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGRST_DB_URI: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      PGRST_DB_SCHEMAS: public
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3001:3000"  # ホストの3001をコンテナの3000にマッピング
    command: ["postgrest"]
    restart: unless-stopped

  auth:
    image: supabase/gotrue:v2.164.0
    container_name: supabase-auth
    depends_on:
      db:
        condition: service_healthy
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      API_EXTERNAL_URL: http://localhost:9998  # ホスト側のポートを9998に変更
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      GOTRUE_SITE_URL: http://localhost:3001
      GOTRUE_JWT_SECRET: ${JWT_SECRET}
    ports:
      - "9998:9999"  # ホストの9998をコンテナの9999にマッピング
    restart: unless-stopped

  studio:
    image: supabase/studio:20241202-71e5240
    container_name: supabase-studio
    depends_on:
      db:
        condition: service_healthy
      meta:
        condition: service_healthy
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      STUDIO_PG_META_URL: http://meta:8080
      SUPABASE_URL: http://localhost:3001
      SUPABASE_PUBLIC_URL: http://localhost:3001
      AUTH_JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8085:3000"  # ホストの8085をコンテナの3000にマッピング
    restart: unless-stopped

  redis:
    image: redis:6.2.14-alpine # Renderのバージョンに合わせる
    container_name: tokitomo-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
