version: "3.9"

services:
  db:
    image: supabase/postgres:15.6.1.146
    container_name: supabase-db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data:Z
    restart: unless-stopped

  meta:
    image: supabase/postgres-meta:v0.84.2
    container_name: supabase-meta
    depends_on:
      db:
        condition: service_healthy
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: db
      PG_META_DB_PORT: 5432
      PG_META_DB_NAME: ${POSTGRES_DB}
      PG_META_DB_USER: postgres
      PG_META_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    restart: unless-stopped

  auth:
    image: supabase/gotrue:v2.164.0
    container_name: supabase-auth
    depends_on:
      db:
        condition: service_healthy
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      API_EXTERNAL_URL: http://localhost:9999
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      GOTRUE_SITE_URL: http://localhost:8081 # studioのポートに変更
      GOTRUE_JWT_SECRET: ${JWT_SECRET}
    ports:
      - "9999:9999"
    restart: unless-stopped

  studio:
    image: supabase/studio:20241202-71e5240
    container_name: supabase-studio
    depends_on:
      db:
        condition: service_healthy
      meta:
        condition: service_healthy
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SUPABASE_ANON_KEY: super-secret-anon # 必要に応じて変更
      SUPABASE_SERVICE_KEY: super-secret-service # 必要に応じて変更
      STUDIO_PG_META_URL: http://meta:8080
      SUPABASE_URL: http://localhost:8085 # studioのポートに変更
      SUPABASE_PUBLIC_URL: http://localhost:8085 # studioのポートに変更
      AUTH_JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8085:3000"
    restart: unless-stopped